// Auto-generated by scripts/sync-firebase-web-config.mjs when you connect the real Firebase project.
// Firebase web configuration is client configuration; authorization is enforced by Auth, Security Rules and App Check.
export const generatedFirebaseConfig = {
  apiKey: '',
  authDomain: 'doc-full-nr.firebaseapp.com',
  projectId: 'doc-full-nr',
  storageBucket: '',
  messagingSenderId: '575211205593',
  appId: '1:575211205593:web:121d906f13a90162341fc8'
} as const;
