import { onCall,HttpsError } from 'firebase-functions/v2/https';
import crypto from 'node:crypto';
import { PDFDocument,StandardFonts,rgb,type PDFFont } from 'pdf-lib';
import fontkit from '@pdf-lib/fontkit';
import QRCode from 'qrcode';
import { requireActive,requireAdmin } from '../shared/auth';
import { db,bucket } from '../shared/firebase';import { audit } from '../shared/audit';import { qrTokenSecret,signPaperToken } from '../shared/qrToken';import { toMs } from '../shared/time';
const region='asia-southeast1'; const bwipjs:any=require('bwip-js');
async function getThaiFont(pdf:PDFDocument):Promise<PDFFont>{try{pdf.registerFontkit(fontkit);const [bytes]=await bucket.file('system/fonts/Sarabun-Regular.ttf').download();return await pdf.embedFont(bytes,{subset:true});}catch{return await pdf.embedFont(StandardFonts.Helvetica)}}
function safeText(font:PDFFont,text:string){try{font.encodeText(text);return text}catch{return text.replace(/[^\x20-\x7E]/g,'?')}}
async function buildPdf(worksheetId:string,userId:string|undefined,codeType:'qr'|'barcode'){
  const ws=await db.doc(`worksheets/${worksheetId}`).get();if(!ws.exists)throw new HttpsError('not-found','ไม่พบใบงาน');const w=ws.data()!;const privateSnap=await db.doc(`worksheetAnswerKeys/${worksheetId}`).get();const totalScore=privateSnap.data()?.totalScore??0;
  const pdf=await PDFDocument.create(),page=pdf.addPage([595.28,841.89]),font=await getThaiFont(pdf);const hex=(w.subjectColor||'#2563EB').replace('#','');const c=rgb(parseInt(hex.slice(0,2),16)/255,parseInt(hex.slice(2,4),16)/255,parseInt(hex.slice(4,6),16)/255);
  page.drawRectangle({x:0,y:790,width:595.28,height:52,color:c});page.drawText(safeText(font,'Nangrong Smart Worksheet'),{x:38,y:808,size:17,font,color:rgb(1,1,1)});page.drawText(safeText(font,`${w.subjectCode||''}  ${w.subjectName||''}`),{x:38,y:758,size:11,font});page.drawText(safeText(font,String(w.title||'Worksheet')),{x:38,y:730,size:16,font});page.drawText(safeText(font,`คะแนนเต็ม: ${totalScore}`),{x:38,y:704,size:10,font});
  if(userId){const us=await db.doc(`users/${userId}`).get();const u=us.data()||{};page.drawText(safeText(font,`ชื่อ: ${u.displayName||'-'}   รหัส: ${u.studentId||'-'}   ห้อง: ${u.classroomName||u.classroomId||'-'}`),{x:38,y:680,size:10,font});}
  let y=630;for(const q of (w.questions||[]).slice(0,8)){page.drawText(safeText(font,`${q.id||''}. ${q.prompt||''}`),{x:38,y,size:10,font,maxWidth:340});y-=58;page.drawLine({start:{x:38,y:y+20},end:{x:380,y:y+20},thickness:.5,color:rgb(.75,.78,.82)});}
  const token=signPaperToken({worksheetId,userId:userId||undefined,issuedAt:Date.now(),nonce:crypto.randomUUID()});let img;if(codeType==='barcode'){const png=await bwipjs.toBuffer({bcid:'code128',text:token,scale:2,height:12,includetext:false});img=await pdf.embedPng(png);}else{const png=await QRCode.toBuffer(token,{type:'png',margin:1,width:300,errorCorrectionLevel:'M'});img=await pdf.embedPng(png);}page.drawImage(img,{x:420,y:620,width:125,height:125});page.drawText(safeText(font,`REF: ${worksheetId}`),{x:38,y:56,size:9,font});page.drawText(safeText(font,'ลงชื่อผู้ส่ง ____________________    ผู้รับ/ผู้ตรวจ ____________________'),{x:38,y:34,size:9,font});return Buffer.from(await pdf.save());
}
export const generatePaperWorksheetPdf=onCall({region,timeoutSeconds:120,memory:'512MiB',secrets:[qrTokenSecret]},async req=>{const a=await requireAdmin(req);const {worksheetId,userId,codeType='qr'}=req.data as any;const bytes=await buildPdf(worksheetId,userId,codeType);const name=`generated-pdf/${worksheetId}/${userId||'blank'}-${Date.now()}.pdf`;await bucket.file(name).save(bytes,{contentType:'application/pdf',metadata:{cacheControl:'private,max-age=0'}});await audit(a,'GENERATE_PDF','worksheet',worksheetId,{userId:userId||null,file:name,codeType});return {ok:true,path:name};});
export const generateMyPaperWorksheetPdf=onCall({region,timeoutSeconds:120,memory:'512MiB',secrets:[qrTokenSecret]},async req=>{const u=await requireActive(req);if(u.role!=='user')throw new HttpsError('permission-denied','User only');const {worksheetId,codeType='qr'}=req.data as any;const ws=await db.doc(`worksheets/${worksheetId}`).get();if(!ws.exists)throw new HttpsError('not-found','ไม่พบใบงาน');const w=ws.data()!;if(w.status!=='published'||w.type!=='paper')throw new HttpsError('failed-precondition','ใบงานยังไม่พร้อม');if(!(w.targetUserIds||[]).includes(u.uid)&&!(w.targetClassroomIds||[]).includes(u.classroomId))throw new HttpsError('permission-denied','ไม่มีสิทธิ์');const open=toMs(w.opensAt);if(open&&Date.now()<open)throw new HttpsError('failed-precondition','ยังไม่ถึงเวลาเปิด');const bytes=await buildPdf(worksheetId,u.uid,codeType);const name=`user-paper/${u.uid}/${worksheetId}/worksheet-${Date.now()}.pdf`;await bucket.file(name).save(bytes,{contentType:'application/pdf',metadata:{cacheControl:'private,max-age=0'}});return {ok:true,path:name};});
