import { onCall,HttpsError } from 'firebase-functions/v2/https';
import { db,FieldValue } from '../shared/firebase';import { requireActive } from '../shared/auth';import { toMs } from '../shared/time';import { audit } from '../shared/audit';import { qrTokenSecret,verifyPaperToken } from '../shared/qrToken';
const region='asia-southeast1';
async function access(uid:string,classroomId:string|undefined,wid:string){const s=await db.doc(`worksheets/${wid}`).get();if(!s.exists)throw new HttpsError('not-found','ไม่พบใบงาน');const w=s.data()!;if(w.status!=='published')throw new HttpsError('permission-denied','ใบงานยังไม่เผยแพร่');if(!(w.targetUserIds||[]).includes(uid)&&!(w.targetClassroomIds||[]).includes(classroomId))throw new HttpsError('permission-denied','ไม่มีสิทธิ์ทำใบงานนี้');return w;}
async function validOverride(uid:string,wid:string){const q=await db.collection('submissionOverrides').where('userId','==',uid).where('worksheetId','==',wid).where('active','==',true).limit(10).get();const now=Date.now();return q.docs.some(d=>{const v=d.data();const until=toMs(v.validUntil);return !until||until>now});}
function enforceWindow(w:any,override:boolean){const now=Date.now(),open=toMs(w.opensAt),due=toMs(w.dueAt);if(open&&now<open)throw new HttpsError('failed-precondition','ยังไม่ถึงเวลาเปิด');if(due&&now>due&&!w.allowLate&&!override)throw new HttpsError('deadline-exceeded','หมดเวลาส่ง');return {now,due,status:due&&now>due?'late':'submitted'} as const;}
export const saveWorksheetDraft=onCall({region},async req=>{const u=await requireActive(req);if(u.role!=='user')throw new HttpsError('permission-denied','User only');const {worksheetId,answers={}}=req.data as any;const w=await access(u.uid,u.classroomId,worksheetId);if(w.saveDraftEnabled!==true)throw new HttpsError('failed-precondition','ไม่เปิดบันทึกร่าง');const id=`${worksheetId}_${u.uid}`;await db.doc(`submissions/${id}`).set({worksheetId,userId:u.uid,status:'draft',answers,updatedAt:FieldValue.serverTimestamp()},{merge:true});return {ok:true,serverTime:Date.now()};});
export const submitDigitalWorksheet=onCall({region},async req=>{const u=await requireActive(req);if(u.role!=='user')throw new HttpsError('permission-denied','User only');const {worksheetId,answers={}}=req.data as any;const w=await access(u.uid,u.classroomId,worksheetId);if(w.type!=='digital')throw new HttpsError('failed-precondition','ไม่ใช่ Digital worksheet');const override=await validOverride(u.uid,worksheetId);const {now,status}=enforceWindow(w,override);const id=`${worksheetId}_${u.uid}`;await db.doc(`submissions/${id}`).set({worksheetId,userId:u.uid,status,answers,submittedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});await audit(u,'SUBMIT_WORKSHEET','submission',id,{worksheetId,status});return {ok:true,status,serverTime:now};});
export const confirmPaperSubmission=onCall({region,secrets:[qrTokenSecret]},async req=>{const u=await requireActive(req);if(u.role!=='user')throw new HttpsError('permission-denied','User only');const {worksheetId,token}=req.data as any;if(!token)throw new HttpsError('invalid-argument','QR/Barcode token required');let p;try{p=verifyPaperToken(token)}catch{throw new HttpsError('invalid-argument','QR/Barcode ไม่ถูกต้อง')}if(p.worksheetId!==worksheetId)throw new HttpsError('invalid-argument','รหัสไม่ตรงกับใบงาน');if(p.userId&&p.userId!==u.uid)throw new HttpsError('permission-denied','เอกสารนี้เป็นของ User คนอื่น');const w=await access(u.uid,u.classroomId,worksheetId);if(w.type!=='paper')throw new HttpsError('failed-precondition','ไม่ใช่ Paper worksheet');const override=await validOverride(u.uid,worksheetId);const {now,status}=enforceWindow(w,override);const id=`${worksheetId}_${u.uid}`;const existing=await db.doc(`submissions/${id}`).get();if(existing.exists&&['submitted','late','reviewed'].includes(existing.data()?.status))throw new HttpsError('already-exists','ยืนยันการส่งไปแล้ว');await db.doc(`submissions/${id}`).set({worksheetId,userId:u.uid,status,paperTokenNonce:p.nonce,submittedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp()},{merge:true});await audit(u,'CONFIRM_PAPER_SUBMISSION','submission',id,{worksheetId,status});return {ok:true,status,serverTime:now};});
