import type { AppUser, Subject, Worksheet } from '../types';
export const demoAdmin:AppUser={uid:'demo-admin',email:'admin@nangrong.ac.th',displayName:'ครูผู้ดูแลระบบ',role:'admin',isActive:true,photoURL:''};
export const demoUser:AppUser={uid:'demo-user',email:'student@nangrong.ac.th',displayName:'นายสมชาย ใจดี',role:'user',isActive:true,studentId:'66309010001',classroomId:'room-1',classroomName:'ปวช.1/1'};
export const subjects:Subject[]=[
 ['20001-1001','สุขภาพความปลอดภัยและสิ่งแวดล้อม','#2563EB'],['20001-1004','กฎหมายแรงงาน','#7C3AED'],['21900-1005','เครือข่ายคอมพิวเตอร์','#0891B2'],['21901-2008','การออกแบบส่วนติดต่อผู้ใช้','#EA580C'],['21901-2017','เทคโนโลยีการนำเข้าข้อมูลเข้าสู่ระบบคอมพิวเตอร์','#16A34A'],['21901-2020','ปฏิบัติงานบริการคอมพิวเตอร์และเทคโนโลยีสารสนเทศ','#DB2777'],['21910-2010','การเขียนโปรแกรมภาษาคอมพิวเตอร์','#4F46E5'],['31901-2001','การออกแบบส่วนติดต่อผู้ใช้ขั้นสูง','#9333EA'],['31901-2004','การพัฒนาซอฟต์แวร์ด้วยเทคโนโลยี Front-End','#0284C7'],['31901-2009','การพัฒนาซอฟต์แวร์สำหรับอุปกรณ์เคลื่อนที่','#0D9488'],['31910-0004','การเขียนโปรแกรมคอมพิวเตอร์','#CA8A04'],['Home Room','กิจกรรมโฮมรูม','#64748B'],['PLC','ชุมชนการเรียนรู้ทางวิชาชีพ','#475569']
].map((x,i)=>({id:`sub-${i+1}`,code:x[0],name:x[1],colorCode:x[2],type:(i<11?'subject':'activity') as 'subject'|'activity',active:true,academicYear:2569,semester:1}));
const future=(hours:number)=>new Date(Date.now()+hours*3600000).toISOString();
export const worksheets:Worksheet[]=[
 {id:'w1',subjectId:'sub-1',subjectCode:'20001-1001',subjectName:'สุขภาพความปลอดภัยและสิ่งแวดล้อม',subjectColor:'#2563EB',title:'การประเมินความปลอดภัยในห้องปฏิบัติการคอมพิวเตอร์',description:'วิเคราะห์ความเสี่ยงและแนวทางป้องกัน',instructions:'ตอบคำถามให้ครบทุกข้อก่อนส่ง',type:'digital',status:'published',totalScore:10,opensAt:future(-24),dueAt:future(2.5),targetClassroomIds:['room-1'],targetUserIds:[],allowLate:false,saveDraftEnabled:true,questions:[{id:'q1',type:'singleChoice',prompt:'ข้อใดเป็นวิธีจัดการสายไฟที่ปลอดภัยที่สุด?',required:true,options:['วางพาดทางเดิน','เก็บเข้ารางสายไฟ','มัดรวมใกล้แหล่งความร้อน']},{id:'q2',type:'paragraph',prompt:'อธิบายวิธีรับมือเมื่อเครื่องดื่มหกใกล้คอมพิวเตอร์',required:true,maxLength:500,pasteDisabled:true}]},
 {id:'w2',subjectId:'sub-3',subjectCode:'21900-1005',subjectName:'เครือข่ายคอมพิวเตอร์',subjectColor:'#0891B2',title:'พื้นฐานระบบเครือข่ายคอมพิวเตอร์',description:'LAN, Router, Switch และ IP Address',instructions:'เลือกคำตอบที่ถูกต้อง',type:'digital',status:'published',totalScore:10,opensAt:future(-48),dueAt:future(26),targetClassroomIds:['room-1'],targetUserIds:[],allowLate:true,saveDraftEnabled:true,questions:[{id:'q1',type:'singleChoice',prompt:'อุปกรณ์ใดใช้เชื่อมต่อหลายอุปกรณ์ใน LAN?',required:true,options:['Switch','Printer','UPS']}]},
 {id:'w3',subjectId:'sub-2',subjectCode:'20001-1004',subjectName:'กฎหมายแรงงาน',subjectColor:'#7C3AED',title:'สิทธิและหน้าที่ตามกฎหมายแรงงาน',description:'ใบงานกระดาษพร้อม QR ยืนยันส่ง',instructions:'พิมพ์ใบงาน ทำบนกระดาษ และสแกน QR เพื่อยืนยันการส่ง',type:'paper',status:'published',totalScore:10,opensAt:future(-72),dueAt:future(72),targetClassroomIds:['room-1'],targetUserIds:[],allowLate:false,saveDraftEnabled:false},
 {id:'w4',subjectId:'sub-7',subjectCode:'21910-2010',subjectName:'การเขียนโปรแกรมภาษาคอมพิวเตอร์',subjectColor:'#4F46E5',title:'ฝึกเขียนคำสั่งเงื่อนไข if...else',description:'ฝึกวิเคราะห์และเขียน JavaScript',instructions:'เขียนโค้ดตามโจทย์',type:'digital',status:'published',totalScore:15,opensAt:future(12),dueAt:future(96),targetClassroomIds:['room-1'],targetUserIds:[],allowLate:false,saveDraftEnabled:true}
];
