import { useEffect,useRef,useState } from 'react';
import type { Question } from '../types';
import { Trash2,UploadCloud } from 'lucide-react';
import { useAuth } from '../context/AuthContext';
import { uploadSubmissionFile } from '../services/storage';

type Props={question:Question;index:number;value:unknown;onChange:(v:unknown)=>void;worksheetId:string};
function CodeEditor({value,onChange,pasteDisabled}:{value:string;onChange:(v:string)=>void;pasteDisabled?:boolean}){const lines=Math.max(1,value.split('\n').length);return <div className="mt-4 grid grid-cols-[44px_1fr] overflow-hidden rounded-xl border border-slate-300 bg-slate-950 text-slate-100"><pre className="select-none border-r border-slate-700 p-3 text-right text-xs leading-6 text-slate-500">{Array.from({length:lines},(_,i)=>i+1).join('\n')}</pre><textarea className="min-h-52 resize-y bg-transparent p-3 font-mono text-sm leading-6 outline-none" value={value} onChange={e=>onChange(e.target.value)} onPaste={e=>{if(pasteDisabled){e.preventDefault();alert('พื้นที่คำตอบนี้ไม่รองรับการวางข้อความ กรุณาพิมพ์คำตอบด้วยตนเอง')}}}/></div>}
function Drawing({value,onChange}:{value:string;onChange:(v:string)=>void}){const ref=useRef<HTMLCanvasElement>(null);const drawing=useRef(false);useEffect(()=>{const c=ref.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#0F172A';},[]);function pt(e:React.PointerEvent<HTMLCanvasElement>){const c=ref.current!,r=c.getBoundingClientRect();return {x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}}function down(e:React.PointerEvent<HTMLCanvasElement>){drawing.current=true;const p=pt(e),ctx=ref.current!.getContext('2d')!;ctx.beginPath();ctx.moveTo(p.x,p.y);ref.current!.setPointerCapture(e.pointerId)}function move(e:React.PointerEvent<HTMLCanvasElement>){if(!drawing.current)return;const p=pt(e),ctx=ref.current!.getContext('2d')!;ctx.lineTo(p.x,p.y);ctx.stroke()}function up(){drawing.current=false;onChange(ref.current?.toDataURL('image/png')||value)}function clear(){if(!confirm('ล้างพื้นที่วาดทั้งหมด?'))return;const c=ref.current!,ctx=c.getContext('2d')!;ctx.clearRect(0,0,c.width,c.height);onChange('')}return <div className="mt-4"><canvas ref={ref} width={900} height={420} className="h-64 w-full touch-none rounded-xl border border-slate-300 bg-white" onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}/><button type="button" className="btn-secondary mt-2" onClick={clear}><Trash2 size={16}/>ล้างพื้นที่วาด</button></div>}
export function QuestionRenderer({question:q,index,value,onChange,worksheetId}:Props){const {user,demoMode}=useAuth();const [progress,setProgress]=useState(0);const [uploading,setUploading]=useState(false);const label=<div className="flex gap-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-blue-50 text-sm font-bold text-blue-700">{index+1}</div><div className="font-semibold">{q.prompt}{q.required&&<span className="ml-1 text-red-600">*</span>}{q.type==='multipleChoice'&&<div className="mt-1 text-xs font-normal text-slate-500">เลือกได้มากกว่า 1 ข้อ</div>}</div></div>;
 const prevent=(e:React.ClipboardEvent)=>{if(q.pasteDisabled){e.preventDefault();alert('พื้นที่คำตอบนี้ไม่รองรับการวางข้อความ กรุณาพิมพ์คำตอบด้วยตนเอง')}};
 return <section className="card">{label}<div className="pl-11">{q.type==='singleChoice'&&<div className="mt-4 space-y-2">{q.options?.map(o=><label key={o} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-3 hover:bg-slate-50"><input type="radio" name={q.id} checked={value===o} onChange={()=>onChange(o)}/><span>{o}</span></label>)}</div>}{q.type==='multipleChoice'&&<div className="mt-4 space-y-2">{q.options?.map(o=>{const arr=Array.isArray(value)?value as string[]:[];return <label key={o} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-3 hover:bg-slate-50"><input type="checkbox" checked={arr.includes(o)} onChange={e=>onChange(e.target.checked?[...arr,o]:arr.filter(x=>x!==o))}/><span>{o}</span></label>})}<button type="button" className="mt-2 text-sm font-semibold text-blue-600" onClick={()=>onChange([])}>ล้างคำตอบ</button></div>}{(q.type==='shortAnswer'||q.type==='paragraph')&&<><textarea className={`field mt-4 ${q.type==='paragraph'?'min-h-36':'min-h-20'}`} maxLength={q.maxLength} value={String(value??'')} onPaste={prevent} onChange={e=>onChange(e.target.value)}/>{q.maxLength&&<div className="mt-1 text-right text-xs text-slate-500">{String(value??'').length}/{q.maxLength} ตัวอักษร</div>}</>}{q.type==='codeEditor'&&<CodeEditor value={String(value??'')} onChange={onChange} pasteDisabled={q.pasteDisabled}/>} {q.type==='drawingArea'&&<Drawing value={String(value??'')} onChange={onChange}/>} {q.type==='matching'&&<div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm text-slate-600">Matching ใช้ Dropdown เป็นรูปแบบสำรองสำหรับมือถือ/คีย์บอร์ดใน Production Editor</div>}{q.type==='fileUpload'&&<div className="mt-4 rounded-xl border-2 border-dashed border-slate-200 p-5"><label className="btn-secondary cursor-pointer"><UploadCloud size={17}/>{uploading?'กำลังอัปโหลด...':'เลือกไฟล์'}<input type="file" className="hidden" disabled={uploading} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>20*1024*1024){alert('ไฟล์ต้องไม่เกิน 20 MB');return;}if(demoMode){onChange({name:f.name,size:f.size,type:f.type,demo:true});return;}if(!user)return;setUploading(true);try{const v=await uploadSubmissionFile(user.uid,`${worksheetId}_${user.uid}`,f,setProgress);onChange(v)}catch(err){alert(err instanceof Error?err.message:'อัปโหลดไม่สำเร็จ')}finally{setUploading(false)}}}/></label>{uploading&&<div className="mt-3 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${progress}%`}}/></div>}{value&&<div className="mt-3 text-sm text-slate-600">ไฟล์: {(value as any).name}</div>}</div>}</div></section>}
